server:
  port: 8089

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:h2:file:/tmp/h2
    username: user
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
  h2:
    console.enabled: truecd
    console.path: /h2-console
  servlet:
    multipart:
      max-file-size: 2MB
  spring:
    servlet:
      multipart:
        max-request-size: 2MB



